# Generated by Django 2.0.5 on 2018-06-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Acronym', models.CharField(max_length=128)),
                ('Location', models.CharField(max_length=128)),
                ('Contact', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem1', models.IntegerField(default=0)),
                ('problem2', models.IntegerField(default=0)),
                ('problem3', models.IntegerField(default=0)),
                ('problem4', models.IntegerField(default=0)),
                ('Total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('dob', models.DateField(blank=True, null=True)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Dbnames', models.CharField(max_length=128)),
                ('dropped_out', models.BooleanField(default=False)),
                ('Colleges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.Colleges')),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.Student'),
        ),
    ]
